### PR TITLE
Parse `self` in expressions.

### PR DESCRIPTION
**Pull request by jonmeow**
`self` wasn't being handled in expression logic, only parameter logic. This is needed for `self.x`.

Also renames SelfDeducedParameter to SelfIdentifier because it's parsed fairly consistently with Identifier; this better represents the situations where `self` will need to be handled, it's where `Identifier` is allowed (although `Identifier` could also refer to a type... but I still think `SelfDeducedParameter` is a more difficult to understand name).

### CODE REVIEW

**Review by zygoloid — APPROVED** [review]
I'm a little concerned that both `self` and `Self` are identifier-like, so this might still be confusing, but this still seems like an improvement to me, and I don't have a better alternative to hand. (`SelfValue` would parallel `SelfType`, but it's an identifier, not a value.)

**Comment by zygoloid** [comment]
Please give this a more useful summary before merging.

**Comment by jonmeow** [comment]
> Please give this a more useful summary before merging.

Added `self` which'd been lost in the commit message (which I'd missed), I'm hoping that's your concern. [also added a little more to the summary]

**Comment by jonmeow** [comment]
I'm querying whether `Self[Type|Value][Identifier|Literal]` might be better, but see #toolchain for that. I'll do a separate PR when we've agreed on another name.

**Pull request merged**
