### PR TITLE
Explorer: fix classes from being destroyed just after `heap.New`

### PR DESCRIPTION
**Pull request by Pixep**
Prevent class destructor from being called immediately when allocating with `heap.New`.

### Details

Relates to #2521 

`heap.New` currently does not create any value, but only an allocation for the value parameter passed to `New`. When creating a class, this results in the destructor of the value returned by `New` being called during the cleanup phase for the scope of `New`.
The behavior is the same for all values (only creating an allocation, but reusing the underlying value*), except their deallocation has no side effect, compared to `NominalClassValue`s.

This PR performs a deep copy of the class (parents included), to avoid the destructor of the rvalue from having side effects on the returned value.

### Alternatives considered

* Create an `LValue` somehow, and use `heap_.Write`
    * not sure if this is easily doable without a rewrite specifically for __intrinsic_new
* Move ownership of the value from the method scope, to the global scope
    * as far as I see, we don't have any similar situation in the code except if we accept to move the entire method and use `ActionStack::MergeScope`. Though probably cleaner, this will likely require more work to make sure this is acceptable and working in all situations.

### CODE REVIEW

**Comment by Pixep** [comment]
I tried a few things, but couldn't come up with the usual lit test, because destructors don't allow mutation. I validated that the value itself is located in a different place in memory, but difficult to show here.

**Comment by zygoloid** [comment]
It looks to me like the problem is that we're running a destructor for `let` bindings. Given:
```
class A {
  destructor [self: Self] {
    // ...
  }
}
fn F(a: A) {}
fn Main() -> i32 {
  var v: A = {};
  F(v);
  return 0;
}
```
... we should only destroy an `A` once, at the end of `Main`. We shouldn't be running a destructor at the end of `F`, because `let` bindings don't create new objects, just new names.

If we were to just disable destructors for `let` bindings, we'll also stop running a destructor for:
```
fn Main() -> i32 {
  let a: A = {};
  return 0;
}
```
That would not be ideal. In that case, I think there are two problems:
1) We don't run destructors for temporary objects. For example, we don't run a destructor for `{} as A;` and we should.
2) We don't implement any kind of lifetime extension / lifetime computation for temporary objects that would let us know /when/ to run the destructor. (Though I guess this is not observable given that we don't run destructors nor mark temporary objects as dead, and there's no way to take the address of one.)

**Comment by Pixep** [comment]
Interesting. I think that is part of it for sure, framing it from a language standpoint. Assuming we update things to handle `let` properly, I think we would still run into issues when using `New` with a temporary (vs lvalue + let), because temporary should be destroyed as you mentioned.

```
// New from rvalue
var new_a = heap.New(A.Create());
```

But in all these situations, the commonality is that `new_a`'s pointee should be an lvalue, unlike currently in explorer. That would solve the practical part of the problem, and then we will still have to address the lifetime of objects and interaction with `let` that you described.

Addressing that first issue would be a good way to fix what this PR was trying to address. But will require creating a new ast node (I believe?). Any recommendations for that? Not sure that's possible from the instrinsic.

**Comment by zygoloid** [comment]
I think we need to rethink the interface of `heap.New`. As-is, I don't think it can avoid there being two separate objects -- the one passed to `heap.New` and the one that's created in the new heap allocation. For example, in `heap.New(A.Create())`, `A.Create` could use `returned var x: A = ...` and observe the address of `x` before `heap.New` is ever invoked, so there's no way that the object created by `A.Create()` can live in the memory allocated by `heap.New`. So unless we expect every heap allocation to perform a destructive move or similar, we're going to end up with two different objects and two destructor calls.

One possible approach would be to pass to `heap.New` a lambda that creates an `A` object, instead of passing it an `A` value. That'd require us to have a sufficiently simple syntax for creating and passing a lambda, as well as sufficiently good performance guarantees for such a scenario (not an indirect call), but I think that's doable. But it depends on several pieces of infrastructure that we don't have yet.

**Comment by Pixep** [comment]
That's good context. I think that part of the design is orthogonal to this particular issue though: when we allocate, we just use the `Value*` (an rvalue here) in the allocation, and destroy it. So we destroy the _actual_ object that we are returning.

This workaround does a deep copy of the value (base et al.) so that the value destroyed, is not the one returned (copied).

**Comment by zygoloid** [comment]
`Value`s don't have identity -- they're not objects, they're just the values held in an object. So making a deep copy of a `Value` doesn't seem like it's achieving anything. The identity of an object corresponds to its `AllocationId`. As far as I can see, the allocation that we're destroying here is the one for the parameter, not the one created by the heap allocation, but it also looks like there's some incorrect code in explorer that tries to map from a `Value*` to an `AllocationId` and just picks up the first object that happens to have the given value, so maybe that's causing problems? (I think `Heap::GetAllocationId` and `RuntimeScope::Bind` should not exist, but we can't quite remove them because that results in infinite recursion in destructors that take `self` by value, because `self` gets destroyed again at the end of the destructor.)

I've tried to craft an example to observe which object is being destroyed during a call to `heap.New`, but have not yet been successful, due to other missing features in `explorer`, such as pointer comparisons or pointer printing. For example: https://carbon.godbolt.org/z/rqWTT4rY9

**Comment by Pixep** [comment]
I confirm `Heap::GetAllocationId` behavior, at least, is incorrect. I had the same issue around pointer comparison in Carbon, and diagnosed the issue by printing the stack value addresses.

Thanks for clarifying the value/allocation id part, that wasn't clear to me.

**Comment by Pixep** [comment]
For visibility: I am looking at ways to drop `Heap::GetAllocationId` entirely now, which is at the core of our issue. Might be in a different PR.

**Comment by Pixep** [comment]
Closing this one, addressed in https://github.com/carbon-language/carbon-lang/pull/2736

**Pull request closed without merging**
