### PR TITLE
Update github_helpers.py

### PR DESCRIPTION
**Pull request by martcpp**
added few comment to enable readability

### CODE REVIEW

**Comment by martcpp** [comment]
added the comment to enable readability

**Review by josh11b — COMMENTED** [review]
I don't see the motivation for these changes, was there some confusion that prompted them?

**Comment by martcpp** [comment]
Yeah, there is a need for it it obfuscating if the former is allowed
approve the new change

**Comment by josh11b** [comment]
Thank you for your interest in Carbon. Unfortunately, without a clear motivation for the change we won't merge the PR.

**Pull request closed without merging**
