### PR TITLE
Update conduct team member list

### PR DESCRIPTION
**Pull request by CelineausBerlin**
deleted @flysand7 from the conduct team member list after they left the team

### CODE REVIEW

**Comment by jonmeow** [comment]
Noting #4392 missed this, had you considered changing one location (either or) to refer to the other, eliminating one copy?

**Comment by CelineausBerlin** [comment]
Good point! I'll look into it. Thank you!

**Comment by CelineausBerlin** [comment]
After touching base with the conduct team, we want to avoid duplicate information, indeed: 
The [conduct team page](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/teams/conduct_team.md) should contain the team breakdown, not the [CoC page](https://github.com/carbon-language/carbon-lang/blob/trunk/CODE_OF_CONDUCT.md). 
So, before we modify the latter, let's update the former (with #4394). 

Then, when this update is done, we'll go and update the [CoC file](https://github.com/carbon-language/carbon-lang/blob/trunk/CODE_OF_CONDUCT.md) so it makes a reference to the conduct team page.

Does that resolve the issue?

**Review by zygoloid — APPROVED** [review]
Sounds reasonable to me.

**Pull request merged**
