### PR TITLE
Removed some extra spaces

### PR DESCRIPTION
**Pull request by aarabii**
Just removed some extra spaces and a comma.

### CODE REVIEW

**Comment by jonmeow** [comment]
We rely on automated formatting for a lot of things, in order to avoid debates over whitespace. Please see the errors:
https://github.com/carbon-language/carbon-lang/runs/7481917209?check_suite_focus=true

The `**TODO**` change is the only one not auto-formatted.

**Comment by aarabii** [comment]
My bad

**Review by jonmeow — CHANGES_REQUESTED** [review]
Following up on the above formatting comment, explicitly requesting changes so that the PR is appropriately marked. Please close if the TODO-only change doesn't seem worthwhile to you, I just don't want to close if you'd still like to make that change.

**Comment by aarabii** [comment]
sorry, my bad I'm still learning to contribute...

**Comment by jonmeow** [comment]
np, a lot of us were new to GitHub when we started this. :)

**Comment by aarabii** [comment]
Thanks, @jonmeow if you need any help or feel lazy to do any task you can ping me here. :)

**Pull request closed without merging**
