### PR TITLE
Third Party `issue_manage` GCP Integration Predecessor 

### PR DESCRIPTION
**Pull request by ghost**
**New contributors may find issue_manage useful for learning Carbon design styles when making contributions. Making a draft pull request now, is more adventurous than waiting until issue_manage achieves full Carbon merge relevancy and compliance.**

Closes _no issue closed_

### CODE REVIEW

**Comment by chandlerc** [comment]
My understanding is that the idea is a tool to manage issues in a way that is easier for newcomers to figure out?

A couple of notes about how to proceed here:

1) I'd generally encourage engaging w/ folks on Carbon's discord server, specifically the #infra channel, to make sure that the approach you have in mind makes sense to the community. That can help avoid duplicate or wasted effort in case a different direction is preferred or a simpler approach uncovered.
2) Beyond that, I'd suggest waiting until you have something pretty close to working and/or a clear agreed-upon direction w/ the community before even a draft PR. You can always iterate on a fork before then. WDYT?

**Comment by ghost** [comment]
A tool to help newcomers was my first thought, yes, that's true. Now this PR is turning into more of a guide for newcomers. Maybe there's a better location than the tools directory. Searched for Carbon on Discord app and nothing shows.

1) Will get involved in that channel as soon as I find Carbons discord. I Agree with you. I'm Activate on GitHub mostly. Simply trying to find a good place for me to start getting involved. There's no waste on my side. issue_manage example contribution is in line with my current development architecture of 'making a custom Carbon, GCP, Firbase integration for an Android app'. The Carbon community may experience waste until I am able to sync with everyone in the proper way. Maybe a link to Carbons discord will show up on my screen soon.

2) I have iterated on a fork and moved away from the tool concept one step by moving into the tools/example directory. This PR works at this time as a follow along example on one way to get going as a newcomer with contributing a tool to Carbon. I Agree with you completely on your perspective. From my perspective, everything looks good. I am being adventurous. Willing to accept a rejected PR. There's no dead ends in a good adventure. Result of inability to integrate at this point will be that I get back into the Issues board again and try to integrate with something fresh, maybe a 'good first issue', and also continue this issue_manage example contribution on a fork because this issue_manage example contribution is definitely relevant from someone with my perspective as a new contributor that's unable to finish a 'good first issue' overnight.

**Comment by eeshvardasikcm** [comment]
A tool to help newcomers was my first thought, yes, that's true. Now this PR is turning into more of a guide for newcomers. Maybe there's a better location than the tools directory. Searched for Carbon on Discord app and nothing shows.

1) Will get involved in that channel as soon as I find Carbons discord. I Agree with you. I'm Activate on GitHub mostly. Simply trying to find a good place for me to start getting involved.

There's no waste on my side. issue_manage example contribution is in line with my current development architecture of 'making a custom Carbon, GCP, Firbase integration for an Android app'. The Carbon community may experience waste until I am able to sync with everyone in the proper way. Maybe a link to Carbons discord will show up soon.

2) I have iterated on a fork and moved away from the tool concept one step by moving into the tools/example directory. This PR works at this time as a follow along example on one way to get going as a newcomer with contributing a tool to Carbon. I Agree with you completely. From my perspective, everything looks good. 

I am being adventurous. Willing to accept a rejected PR. There's no dead ends in a good adventure.

Result of inability to integrate at this point will be that I get back into the Issues board again and try to integrate with something fresh, maybe a 'good first issue', and also continue this issue_manage example contribution on a fork because this issue_manage example contribution is definitely relevant from someone with my perspective as a new contributor that's unable to finish a 'good first issue' overnight.

**Comment by ghost** [comment]
> 2) Beyond that, I'd suggest waiting until you have something pretty close to working and/or a clear agreed-upon direction w/ the community before even a draft PR.

Reading, comprehending, and realizing the _entire_ contribution guidelines, including all referenced and linked materials appears to be a two year task for busy people. I'm only capable of absorbing a little at a time, being aware of the chance that this PR may not be following guidelines.

Tools category says guidelines not required to be followed. Governance has roadmap control. My PR is morphing into something less like a tool and more like a guide. Guides probably would be covered under requirements for a new proposal. My focus so far is from the perspective of welcoming a community that desires to get involved in actively making successful pull requests.

Roadmap probably has a tool like my GCP integration moving to active in 18 months; and irrelevant today.

Maybe this topic can only stay currently active if it's translated into a document proposal? If there's currently not a simple guide on getting started as a new contributor? Does joining the Carbon Discord server solve this issue? Would adding a clear path or link to the Discord server be helpful?

I'm still new here. These are only some thoughts. Personally, my psychological well-being is optimistic in facing obstacles, but I can't speak for everyone in the community in that regard.

**Comment by eeshvardasikcm** [comment]
> 2) Beyond that, I'd suggest waiting until you have something pretty close to working and/or a clear agreed-upon direction w/ the community before even a draft PR.

Reading, comprehending, and realizing the _entire_ contribution guidelines, including all referenced and linked materials appears to be a two year task for busy people. I'm only capable of absorbing a little at a time, being aware of the chance that this PR may not be following guidelines.

Tools category says guidelines not required to be followed. Governance has roadmap control. My PR is morphing into something less like a tool and more like a guide. Guides probably would be covered under requirements for a new proposal. My focus so far is from perspective of welcoming a community that desires to get involved in actively making successful pull requests.

Roadmap probably has a tool like my GCP integration moving to active in 18 months; and irrelevant today.

Maybe this topic can only stay currently active if it's translated into a document proposal? If there's currently not a simple guide on getting started as a new contributor? Does joining the Carbon Discord server solve this issue? Would adding a clear path or link to the Discord server be helpful?

I'm still new here. These are only some thoughts. Personally, my psychological well-being is optimistic in facing obstacles, but I can't speak for everyone in the community in that regard.

**Comment by ghost** [comment]
Closing request.

Without the need for additional time from leads on this pull request, I will go ahead and dictate the direction of this PR and close with interest in moving to newly influenced conclusions sourced from comment by lead.

`issue_manage` would be better suited as a proposal for Carbon guides to be updated with additional details about how to be a new contributor. Leads imply that discussion on Discord may be a good start before making a proposal like this.

`issue_manage` will not be continued and instead will be replaced with a subsequent GCP integration tool featuring basic interfaces to Firebase, Cloud Functions and Stack Driver to begin with.

No proposal will be made for improved Contribution guides until Discord discussion and additional research by myself prove some need for such proposal.

I will try to get involved with a `good first issue` as a more immediately needed Carbon engagement.

**Comment by ghost** [comment]
Additionally, some more closure on this PR and any subsequent tool development stemming from this PR.

Current design states that a package management tool would be one possibility for a tool, if that tool would even be necessary.

Development of GCP integration using firebase appears to lie outside of Carbon language development. My GCP Carbon integration will be moved to one of my private repositories.

Anyone interested in following along with my original intent in this PR, can follow along with PRs made by new contributors in the `good first issue` category.

I will be going active on a `good first issue` sometime within the next few weeks.

**Comment by ghost** [comment]
Remaining issue becomes "waste". This work is done. I will have to lookup a lead directly on Discord as soon as possible. I saw a link to his Discord on one of the inactive `good first issues `. Thought it would be easier to acquire a generalized Carbon server link for the discord. The md files that I detailed could be converted into some valuable additions to the current docs, possibly the contributor pages. To avoid using any more lead time on these concerns, I'm going to try and get involved in a `good first issue` right away. Hopefully that will make lead involvement meaningful through this entire process begining with my generalized comments on recent issues. My schedule will become a little packed. I'm excited to start making valuable and consistent contributions to Carbon. The adventurous nature of getting right in there and not being afraid to make mistakes is hard for me to defeat.

**Pull request closed without merging**
