### PR TITLE
Add Abstract Section

### PR DESCRIPTION
**Pull request by camio**
Reading through extensive problem and background documentation before seeing
what is being proposed is tedious for a reader. An abstract section at the
beginning of a document that provides a succinct summary helps a lot. We
propose adding such a section to our proposal template.

### CODE REVIEW

**Review by chandlerc — APPROVED** [review]
LG, no controversy here so this is fine to go in.

(And for the record, Jon is probably right and this didn't need a proposal.)

**Review by zygoloid — APPROVED** [review]

**Comment by jonmeow** [comment]
Just to give my two cents -- I'd suggest removing the proposal file. This isn't really following the proposal process (e.g., leads aren't asking for rationale), and while I don't think that's necessary, I think the proposal file becomes a distraction and could become a poor example for others.

**Review by chandlerc — CHANGES_REQUESTED** [review]
Jon raised a good point, let's remove the proposal file before merging. Marking as needing a change.

**Comment by chandlerc** [comment]
Just a gentle ping here as I'm adding an abstract to another proposal manually. =] Also happy for someone else to help if needed.

**Review by jonmeow — APPROVED** [review]

**Review by chandlerc — APPROVED** [review]
LG (sorry I missed that this was blocked on me)

**Pull request merged**
