### PR TITLE
Are We Explorer Yet?

### PR DESCRIPTION
**Pull request by camio**
It is currently difficult to see the status of Carbon explorer and where effort
is needed. We propose creating a AreWeYet-styled dashboard to address this.

### CODE REVIEW

**Review by chandlerc — COMMENTED** [review]
FWIW, I love it. =]

What do you think about moving the proposed are-we-yet dashboard out of the proposal and just a part of this PR in the place you imagine it going? (I'm guessing in or next to the explorer readme, but maybe other places make more sense like in the project docs directory?) Maybe there is more work you want to do before actually landing it and so its good to just get directional approval here, really up to you.

**Comment by jonmeow** [comment]
> FWIW, I love it. =]
> 
> What do you think about moving the proposed are-we-yet dashboard out of the proposal and just a part of this PR in the place you imagine it going? (I'm guessing in or next to the explorer readme, but maybe other places make more sense like in the project docs directory?) Maybe there is more work you want to do before actually landing it and so its good to just get directional approval here, really up to you.

Just to note from the proposal: "In summary, we propose the creation of a new page on the carbon-lang Wiki called
“Are We Explorer Yet?”"

I think @camio had been hesitant to create the wiki without leads approval (it would not be atomic with this change, unlike a file in the repo): are leads accepting the proposal?

**Comment by jonmeow** [comment]
To update here: https://github.com/carbon-language/carbon-lang/wiki/Are-we-explorer-yet%3F

**Review by chandlerc — APPROVED** [review]
Approving for leads.

**Comment by chandlerc** [comment]
(Not merging in case there are trivial updates to URLs or something that need to happen before it merges.)

**Comment by chandlerc** [comment]
(merging after confirmation nothing else is needed)

**Pull request merged**
