### PR TITLE
Change contribution_tools.md to refer to toolchain instead of explorer

### PR DESCRIPTION
**Pull request by jonmeow**

### CODE REVIEW

**Review by chandlerc — COMMENTED** [review]
Doh, for some reason I thought this had already been merged when I was sending out #3532 -- sorry about that.

What would work best? Landing this first, and then looking at #3532? Folding this into #3532? Largely happy to do whatever is eaisest here, no strong opinion.

**Comment by chandlerc** [comment]
@zygoloid for thoughts on how best to land these.

**Comment by zygoloid** [comment]
Sorry about the merge conflicts with #3532. Given that that PR includes the proposal for the change in direction I've gone ahead and merged it, but I think we should take the changes here too (at least the ones that aren't completely overlapping).

**Comment by jonmeow** [comment]
The only non-overlapping change seems to be the one to contribution_tools.md, so I've reverted other work.

**Review by zygoloid — APPROVED** [review]

**Pull request merged**
