### PR TITLE
Update .pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by madhupashish**
updated with latest Version

**Replace this paragraph with a description of what this PR is changing or
adding, and why.**

Closes #ISSUE

### CODE REVIEW

**Comment by madhupashish** [comment]
Must Review This Code

**Review by madhupashish — COMMENTED** [review]
new

**Comment by jonmeow** [comment]
I think it should go without saying, but the delta here (both removing useful checks, and adding unrelated ones) is not appropriate.

@madhupashish Please consider the changes you're making. It's disruptive to provide changes like this. To be clear, repeat instances will result in us blocking you from making contributions.

**Comment by jonmeow** [comment]
I want to add, if you want to better understand what's expected for contributions, it may be good to reach out on Discord. It can be a bit easier to hold a discussion than on GitHub. https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#collaboration-systems

**Pull request closed without merging**
