### PR TITLE
Rework of .devcontainer (#1816)

### PR DESCRIPTION
**Pull request by beryll1um**
Development container image was changed to `homebrew/brew`.

### CODE REVIEW

**Comment by geoffromer** [comment]
It would probably be good to get @cyw3's take on this, since they wrote #1608

**Review by pradeepkumar-buku — APPROVED** [review]

**Comment by beryll1um** [comment]
> It would probably be good to get @cyw3's take on this, since they wrote #1608

+, @cyw3's seems to understand a lot about this topic
I still don't understand purpose of some solutions, like building git and curl tools in container.
It might be cool to build and push a container specifically for carbon-lang. I'll be glad to do it with (him/her).

UPD: Linked.

**Comment by aandevski** [comment]
_Disclaimer: I'm only familiar with the basics of dockerfiles and it's my first time using `.devcontainer`._

I prefer this version of `.devcontainer` over the current one. Primarily because it's cleaner, making it easier to read and maintain. Also, the current one also doesn't work for me right now, (seems to be failing on the `brew install --force-bottle --force --verbose llvm` step) while this one works properly.

The only issue that I currently have with this one is that the `clangd` extension is having some hiccups, not being able to find includes like `<gmock/gmock.h>` and `<benchmark/benchmark.h>` and thus showing extra errors. However, this only affects the VSCode extension and bazel seems to work fine.

**Review by jonmeow — APPROVED** [review]
Thanks, this seems like a good & significant simplification.

**Comment by jonmeow** [comment]
> The only issue that I currently have with this one is that the `clangd` extension is having some hiccups, not being able to find includes like `<gmock/gmock.h>` and `<benchmark/benchmark.h>` and thus showing extra errors. However, this only affects the VSCode extension and bazel seems to work fine.

This might be a compilation database issue which running ./scripts/create_compdb.py could help with (creating/refreshing the db)

**Comment by jonmeow** [comment]
(and sorry, didn't actually mean to merge yet, too many attractive green buttons -- please follow up with me with concerns, I'm happy to talk through the approach options here, even though my grasp of devcontainer is very limited)

**Comment by cyw3** [comment]
> > It would probably be good to get @cyw3's take on this, since they wrote #1608
> 
> +, @cyw3's seems to understand a lot about this topic I still don't understand purpose of some solutions, like building git and curl tools in container. It might be cool to build and push a container specifically for carbon-lang. I'll be glad to do it with (him/her).
> 
> UPD: Linked.

Nice update. 

In order to building `homebrew` in `centos`, building `git` and `curl` tools is necessary.

For me, based on a reliable basic OS image, and then showing each step of the environment installation steps, such a dockerfile is safe, intuitive and clean.

**Comment by beryll1um** [comment]
> ./scripts/create_compdb.py

Yep. I faced with the same problem, and `create_compdb.py` solve it.

**Comment by beryll1um** [comment]
> > > It would probably be good to get @cyw3's take on this, since they wrote #1608
> > 
> > 
> > +, @cyw3's seems to understand a lot about this topic I still don't understand purpose of some solutions, like building git and curl tools in container. It might be cool to build and push a container specifically for carbon-lang. I'll be glad to do it with (him/her).
> > UPD: Linked.
> 
> Nice update.
> 
> In order to building `homebrew` in `centos`, building `git` and `curl` tools is necessary.
> 
> For me, based on a reliable basic OS image, and then showing each step of the environment installation steps, such a dockerfile is safe, intuitive and clean.

Another question: why are you specifying the installation of the `libxcrypt` package in a previous version of the Dockerfile?
I can assume that this is a replacement for zlib1g-dev, but I'm not sure..

Can you verify my assumption?

**Pull request merged**
