### PR TITLE
Fix Devcontainer build errors

### LINKED ISSUE #4065: Error while building docker image as part of devcontainer
When use VS Code to open the carbon-lang directory inside the devcontainer, I get the following error during image build:

```
[2024-06-19T20:19:22.284Z] Errors were encountered while processing:

 /tmp/apt-dpkg-install-nzc56z/31-libclang-rt-15-dev_1%3a15.0.7~++20231019083512+8dfdcc7b7bf6-1~exp1~20231019203551.119_amd64.deb

 /tmp/apt-dpkg-install-nzc56z/38-libpolly-15-dev_1%3a15.0.7~++20231019083512+8dfdcc7b7bf6-1~exp1~20231019203551.119_amd64.deb
[2024-06-19T20:19:22.407Z] E: Sub-process /usr/bin/dpkg returned an error code (1)
[2024-06-19T20:19:28.922Z] Error: building at STEP "RUN ./llvm.sh 15 all": while running runtime: exit status 100
```

I can attempt to update the base ubuntu image and clang versions and send a pull request if this is a valid issue.

### PR DESCRIPTION
**Pull request by nirmal-j-patel**
Devcontainer Dockerfile has been updated to use Ubuntu 24.04 as the base. Now devcontainer builds without errors. Tested with Podman on Linux and Docker Desktop on Windows.

To avoid re-downloading and re-compiling whenever the container is deleted, a named volume is mounted at /home/ubuntu/.cache.

Closes #4065

### CODE REVIEW

**Comment by jonmeow** [comment]
To be sure, we do require a signed CLA for all contributions (details [here](https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#contributor-license-agreements-clas)). Can you please let us know when you've signed it?

**Comment by nirmal-j-patel** [comment]
> To be sure, we do require a signed CLA for all contributions (details [here](https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#contributor-license-agreements-clas)). Can you please let us know when you've signed it?

I signed the CLA after I created this pull request. Is there any other action that I need to do to confirm that I agree with the CLA?

Thanks.

**Comment by jonmeow** [comment]
When you signed the CLA, did you associate your GitHub account with it? You can check by:

1. Go to https://cla.developers.google.com/clas
2. Click on "Edit Contact Information"
3. Look under "GitHub Username"

(note, https://github.com/carbon-language/carbon-lang/pull/4647/checks?check_run_id=34055884013 also includes some diagnostic info)

**Comment by nirmal-j-patel** [comment]
I added my GitHub Username and it appears to be working fine now (https://github.com/carbon-language/carbon-lang/pull/4647/checks)

**Review by jonmeow — APPROVED** [review]
Thanks! I'm happy to see this updated to work again.

As a sidenote, we may want to revisit this in a half a year or so to see if people are using it, given how long it was sitting around non-functional.

**Pull request merged**
