### PR TITLE
Typo Fixes

### PR DESCRIPTION
**Pull request by kku77**

### CODE REVIEW

**Review by ooxi — COMMENTED** [review]
I would have preferred *History can manually be copied*

**Comment by ooxi** [comment]
Those changes look good to me!

**Review by ooxi — APPROVED** [review]

**Review by antonioanerao — APPROVED** [review]

**Comment by josh11b** [comment]
It is best not to change the wording of the proposals after they have been accepted. If it was just typo fixes that would probably be okay, but some of these changes are more than just typo fixes. Also, the formatting would need to be updated to pass the pre-commit checks. Please follow the [contributing instructions to setup pre-commit](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#pre-commit) so that prettier can automatically apply fixes.

**Review by abdullahkavakli — APPROVED** [review]

**Review by MrKrishnaAgarwal — COMMENTED** [review]
@kku77 
Pre Commit Check is Required else your pull request cannot be merged

Run pre commit in your local client and then create or push the changes here.

**Comment by jonmeow** [comment]
I'm closing this PR because it's been sitting with an unaddressed review from josh11b for a couple weeks now. It can be reopened if issues Josh's comments are addressed, but josh11b explained, proposals are mainly there for historical purposes: we're going to be conservative about modifying them.

**Pull request closed without merging**
