### PR TITLE
Do Not Lead People to GitHub Discussion

### PR DESCRIPTION
**Pull request by micttyl**
Currently gather every discussions into Discord

### CODE REVIEW

**Comment by geoffromer** [comment]
Why shouldn't people use GitHub discussions?

**Comment by jonmeow** [comment]
> Why shouldn't people use GitHub discussions?

I think it's more like "To join the design discussion" is kind of misleading.

@zygoloid Thoughts on this?

**Comment by micttyl** [comment]
> Why shouldn't people use GitHub discussions?

Seems to be right. I thought it could be better to focus the redundant posting sites of the same topic into a single place. I saw @zygoloid using Discord screenshots to whom presumably not aware of it. Such a case is possibly due to this disperse of discussion sites(I don't see people talking in GitHub Discussion. Maybe this community is not active anymore?). In addition, I don't remember exactly, but I was also told that the most of discussions take place in Discord, so it is recommended to join.

No absolute closure here. Given this change, we don't shut down GitHub discussion. We design so that a first-visiting README reader does not weight heavier on GitHub discussion than that of Discord by reading this section, which is what we may want to say.

The entry barrier is eased out. Recently we removed the phone verification. This means the Discord participation now requires the same number of identification factor(only email address, possibly the recycle of the same email for GitHub).

**Review by zygoloid — APPROVED** [review]
Yes, I agree with this change. We perform most of our design discussions on Discord, and it's misleading to suggest that people use GitHub discussions for this, and especially to mention that before mentioning Discord.

I wouldn't mind keeping a mention of GitHub discussions, saying that that's only for user discussions and Q&A but that design discussions happen on Discord, but this change looks like an improvement to me.

**Comment by jonmeow** [comment]
> I wouldn't mind keeping a mention of GitHub discussions, saying that that's only for user discussions and Q&A but that design discussions happen on Discord, but this change looks like an improvement to me.

FWIW I think it's probably worth brining back once we're more ready for developers to use Carbon. Right now I think emphasizing user discussions and Q&A might imply Carbon's more ready than it is.

**Pull request merged**
