### PR TITLE
edit wrong file name & suggest editing drive document

### PR DESCRIPTION
**Pull request by i-Sa3ed**
More important, the link in (Toolchain architecture drive file => diagnostic registry) should be updated

**Replace this paragraph with a description of what this PR is changing or
adding, and why.**

Closes #ISSUE

### CODE REVIEW

**Review by jonmeow — APPROVED** [review]
Thanks! I missed this when renaming.

**Comment by i-Sa3ed** [comment]
I think there is something wrong..
when I tried to commit "fix typo" I was intended to make a new PR, but it's added to the previous unmerged PR !
how can I solve it?
@jonmeow

**Comment by jonmeow** [comment]
> I think there is something wrong.. when I tried to commit "fix typo" I was intended to make a new PR, but it's added to the previous unmerged PR ! how can I solve it? @jonmeow

It's fine, this is already a typo fix PR so I'll just add a note to the PR description when merging.

For future reference, you could either:

1. Undo the change (e.g., `git checkout trunk <path>`), commit, and push
2. Undo the commit (`git reset --soft HEAD~1`) and force push

**Comment by i-Sa3ed** [comment]
> > I think there is something wrong.. when I tried to commit "fix typo" I was intended to make a new PR, but it's added to the previous unmerged PR ! how can I solve it? @jonmeow
> 
> It's fine, this is already a typo fix PR so I'll just add a note to the PR description when merging.
> 
> For future reference, you could either:
> 
> 1. Undo the change (e.g., `git checkout trunk <path>`), commit, and push
> 2. Undo the commit (`git reset --soft HEAD~1`) and force push

Thanks a lot..

**Pull request merged**
