### PR TITLE
Add missed header.

### PR DESCRIPTION
**Pull request by mirmik**
It fix failed build for me.

### CODE REVIEW

**Comment by chandlerc** [comment]
Thanks for sending the PR, but will need to sign the CLA as mentioned before we can review or merge.

**Review by chandlerc — CHANGES_REQUESTED** [review]
Thanks for sending the PR, but will need to sign the CLA as mentioned before we can review or merge.

**Comment by mirmik** [comment]
> Thanks for sending the PR, but will need to sign the CLA as mentioned before we can review or merge.

have done

**Review by chandlerc — APPROVED** [review]
Good catch, and thanks!

**Pull request merged**
