### PR TITLE
Add the languages' successors shown in Chandler's talk to main README

### PR DESCRIPTION
**Pull request by urielgarciarivas**
Add `C → C++` and `Objective-C → Swift` to main README as shown in [Chandler's talk](https://www.youtube.com/watch?v=omrY53kbVoA).

### CODE REVIEW

**Comment by jonmeow** [comment]
Hi! The README's content differs from the presentation because we're trying to write a more succinct story, and it would be expensive (space-wise) to talk about the trade-offs of various approaches in the same way that we do in presentations. The list isn't intended to be exhaustive, and so we'd prefer not to add Swift. See also #1721.

**Comment by urielgarciarivas** [comment]
Not adding Swift sounds reasonable and I totally agree with the approach of writing a more succinct story, does the same apply to `C → C++`?

**Comment by jonmeow** [comment]
I'm going to try harder to pass that question to @chandlerc

**Comment by urielgarciarivas** [comment]
😅

**Comment by chandlerc** [comment]
Finally getting back here, sorry for all the delays.

> Not adding Swift sounds reasonable and I totally agree with the approach of writing a more succinct story, does the same apply to `C → C++`?

I think yes, if for different reasons.

Here, I think the history is just much more complicated. Again, in the presentation we're able to talk through these things and then re-focus on the later examples. We're also telling a much more nuanced story of different approaches from Carbon's.

I think focusing on the most similar in goals, and especially in the case of "Java -> Kotlin" approach in the README makes a lot of sense.

I'm going to close for now. That said, if there is really significant interest in shifting approach here across the community or especially of the other @carbon-language/carbon-leads would prefer a different approach we can definitely re-open and look at this or similar adjustments.

**Pull request closed without merging**
