### PR TITLE
Enable misc-non-private-member-variables-in-classes and adjust style to match

### PR DESCRIPTION
**Pull request by jonmeow**
Pursuant to discussion regarding #4699, turn on `misc-non-private-member-variables-in-classes` using the `IgnoreClassesWithAllMemberVariablesBeingPublic` flag (the check treats structs as classes, so we need this for structs with all-public members). Updates the style guide notes to match, which should be pretty minor due to the scoping of test fixtures.

Also fixes some underscore uses in test files on the way. Basically this is keeping the style for [class data member naming](https://google.github.io/styleguide/cppguide.html#Variable_Names) even while making them public.

### CODE REVIEW

**Comment by jonmeow** [comment]
Sidenote here, I played around with:

```
  - key: readability-identifier-naming.ClassMemberSuffix
    value: _
```

but AFAICT it doesn't catch anything. I'm actually not sure if the readability identifier naming is firing much for class members.

**Comment by chandlerc** [comment]
> Also fixes some underscore uses in test files on the way. Basically this is keeping the style for [class data member naming](https://google.github.io/styleguide/cppguide.html#Variable_Names) even while making them public.

Given that there's no need for an accessor, it would make a bit more sense to make the rule be that fixtures either:

a) Are a struct with all members public, and no `_` suffix needed, or
b) Are a class with members private, using `_`, and have getters for accesses in tests.

WDYT?

**Comment by jonmeow** [comment]
> > Also fixes some underscore uses in test files on the way. Basically this is keeping the style for [class data member naming](https://google.github.io/styleguide/cppguide.html#Variable_Names) even while making them public.
> 
> Given that there's no need for an accessor, it would make a bit more sense to make the rule be that fixtures either:
> 
> a) Are a struct with all members public, and no `_` suffix needed, or b) Are a class with members private, using `_`, and have getters for accesses in tests.
> 
> WDYT?

Structs have a separate rule about being passive data holders: https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes

Beyond inheriting from the test fixture base class, some of the test fixtures have constructors/destructors, helper methods, etc. To me, making these structs would be a bigger change from style.

I'm also not eager to do (b) -- it just feels like we'd be writing accessors for most members. I could do that if you dislike the `public` solution, but I think it'd discourage test fixtures in general.

**Comment by chandlerc** [comment]
> > > Also fixes some underscore uses in test files on the way. Basically this is keeping the style for [class data member naming](https://google.github.io/styleguide/cppguide.html#Variable_Names) even while making them public.
> > 
> > 
> > Given that there's no need for an accessor, it would make a bit more sense to make the rule be that fixtures either:
> > a) Are a struct with all members public, and no `_` suffix needed, or b) Are a class with members private, using `_`, and have getters for accesses in tests.
> > WDYT?
> 
> Structs have a separate rule about being passive data holders: [google.github.io/styleguide/cppguide.html#Structs_vs._Classes](https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes)
> 
> Beyond inheriting from the test fixture base class, some of the test fixtures have constructors/destructors, helper methods, etc. To me, making these structs would be a bigger change from style.

I think I just don't like this distinction for test fixtures...

My problem is that members of the test fixture are often the very public API of the fixture. Having `_`s makes them feel like they aren't.

But they *do* have invariants, and so the style guide says they can't be `struct`s. =/

I guess if we're going to exempt test fixtures  to the "protected" rule in the style guide, I would prefer to also exempt them from the naming convention, except that it makes it hard to enforce the naming convention consistently. So I was wondering about exempting them to the "no invarianst" rule between `struct` and `class`.

But I don't feel strongly here. I guess we can just have the `_`.

> 
> I'm also not eager to do (b) -- it just feels like we'd be writing accessors for most members. I could do that if you dislike the `public` solution, but I think it'd discourage test fixtures in general.

Definitely would want (b) to be common or the default, agree it's too verbose.

**Review by chandlerc — APPROVED** [review]
LG

**Comment by jonmeow** [comment]
> My problem is that members of the test fixture are often the very public API of the fixture. Having `_`s makes them feel like they aren't.

FWIW, I think the distinction for me is I don't think of the members of a non-inherited test fixture as "public". Instead, I think of TEST_F as something that, if it could be, would be implemented as member functions instead of subclasses (like it is in Python) -- and everything else is glue because of the test framework design.

**Comment by jonmeow** [comment]
NB, rebased due to the clang-tidy-16 format changes.

**Review by chandlerc — APPROVED** [review]
(still LG)

**Pull request merged**
