### PR TITLE
Test `class` with multiple `extend`

### PR DESCRIPTION
**Pull request by josh11b**
Adds coverage for an existing diagnostic. Code appears to work without modification.

### CODE REVIEW

**Comment by josh11b** [comment]
It is complaining that a test that I thought was succeeding because of no diagnostics is actually failing (and does not start with `fail_`). I'm investigating.

**Comment by jonmeow** [comment]
You just need `library "[[@TEST_NAME]]"`

**Comment by josh11b** [comment]
> library "[[@TEST_NAME]]"

Thanks, should be fixed now.

**Comment by josh11b** [comment]
I just realized some comments need to be updated too.

**Comment by josh11b** [comment]
> I just realized some comments need to be updated too.

Done now.

**Review by jonmeow — APPROVED** [review]

**Pull request merged**
