### PR TITLE
Put python object definition and assignment on same line

### PR DESCRIPTION
**Pull request by claytongearhart**
Where there was an object initialization immediately followed by assignment I condensed it to one line, which seems to be the convention looking at other files. I also deleted the repetition of 'of' in some c++ comments because it was grammatically incorrect.

### CODE REVIEW

**Review by josh11b — APPROVED** [review]

**Comment by josh11b** [comment]
Please fix the pre-commit errors.

**Comment by josh11b** [comment]
I'm going on vacation, so please find someone else to merge this when it is ready.

**Comment by claytongearhart** [comment]
I don't really understand why black failed last time, but I successfully ran black locally and tested the pre-commit job with act so I hope it doesn't fail again.

**Review by chandlerc — APPROVED** [review]
LG to me as well, and passes the pre-commit checks now!

Thanks for the contribution, merging!

**Pull request merged**
