### PR TITLE
Replace the toolchain README with a docs link.

### PR DESCRIPTION
**Pull request by jonmeow**
The doc is more up-to-date than the readme right now, and I'm not ready to migrate it back for the moment, but this should at least make it clear what the status is.

### CODE REVIEW

**Review by Pixep — APPROVED** [review]
Content looks good, link valid and accessible to everyone it seems 👍

**Comment by mon-jai** [comment]
@jonmeow @Pixep The mentioned document seems to be private and inaccessible.

**Comment by jonmeow** [comment]
Interesting, Google seems to require the resourcekey part of the url now (this wasn't always the case):
https://docs.google.com/document/d/1RRYMm42osyqhI2LyjrjockYCutQ5dOf8Abu50kTrkX0/edit?resourcekey=0-kHyqOESbOHmzZphUbtLrTw should work (checked in incognito mode)

**Comment by jonmeow** [comment]
Fixing in #2565

**Pull request merged**
