### PR TITLE
Set `me_value` even when accessing a type

### PR DESCRIPTION
**Pull request by geoffromer**

### CODE REVIEW

**Comment by geoffromer** [comment]
No new test coverage is needed; several of our existing tests would have caught the issue if we ran them under MSan.

**Comment by jonmeow** [comment]
I'd considered this initially on #3019 but @zygoloid argued me out of it. Note that if me_value is unconditionally set, then the std::optional should be reverted.

**Comment by jonmeow** [comment]
Also, can you just confirm that the msan issue is still seen after #3019?

**Comment by geoffromer** [comment]
Yep, this is redundant with #3019, which fixes the msan issue.

**Pull request closed without merging**
