### PR TITLE
Rename Directive->Decl in general, BindExport->ExportDecl

### PR DESCRIPTION
**Pull request by jonmeow**
Mechanically, replacing Directive->Decl, directive->declaration, _declaration->_decl (to avoid comments).

Context: https://discord.com/channels/655572317891461132/963846118964350976/1241145948625703062

### CODE REVIEW

**Comment by jonmeow** [comment]
Depends on #3955 [ed: now merged]

**Comment by chandlerc** [comment]
Title says "BindExport -> BindDecl", I think it should be "... -> ExportDecl"

**Comment by jonmeow** [comment]
> Title says "BindExport -> BindDecl", I think it should be "... -> ExportDecl"

Thanks, fixed

**Review by chandlerc — APPROVED** [review]
LG

**Pull request merged**
