### PR TITLE
Begin publishing CoC and moderation transparency reports.

### PR DESCRIPTION
**Pull request by chandlerc**
Proposes a documented cadence, publishing target, and template for Code of Conduct and moderation transparency reports.

Based on the initial proposal draft from @CelineausBerlin.

### CODE REVIEW

**Review by CelineausBerlin — CHANGES_REQUESTED** [review]
"we are still to figure out the basics and principles together _because_ we can automate more now" should be "we are still to figure out the basics and principles together _**before**_ we can automate more now", the sentence was wrong in the Google Doc, sorry about that. Now it makes more sense, doesn't it?

**Comment by chandlerc** [comment]
> "we are still to figure out the basics and principles together _because_ we can automate more now" should be "we are still to figure out the basics and principles together _**before**_ we can automate more now", the sentence was wrong in the Google Doc, sorry about that. Now it makes more sense, doesn't it?

Done with a slight tweak to make it read even better I hope?

Also, since this seems in the right direction, marking it as ready for review. Hopefully this can be fairly quick as folks have already looked at it.

**Comment by chandlerc** [comment]
Updated with an initial suggested cadence. Note that this is easy for us to change in the future if the current suggestion -- quarterly -- doesn't work out.

**Review by zygoloid — COMMENTED** [review]
Looks good to me.

**Comment by chandlerc** [comment]
Just relaying an offline message here from @KateGregory - she said this LG. If Richard or Celine want to approve I'll merge. =D

**Review by CelineausBerlin — APPROVED** [review]

**Review by KateGregory — APPROVED** [review]

**Pull request merged**
