### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by justzh**
**Replace this paragraph with a description of what this PR is changing or
adding, and why.**

Closes #ISSUE

### CODE REVIEW

**Comment by justzh** [comment]
this is fine

**Comment by justzh** [comment]
Be careful when using gcc and make...

**Comment by justzh** [comment]
I think this was great.

**Comment by chandlerc** [comment]
You've made several comments across several issues and PRs that don't seem on topic or relevant, and this PR also doesn't seem on-topic.

If you'd like to contribute, great, but please stay on-topic. If you continue to post off-topic comments, we'll have to block you. I'm closing this PR and locking it.

**Pull request closed without merging**
