### PR TITLE
Fix typo in svg image #1647

### PR DESCRIPTION
**Pull request by pacion**
There was an extra ')' when calling function QuickSort, switched files and uploaded google drive image.

### CODE REVIEW

**Comment by pacion** [comment]
Any idea why pre-commite failed on svg?
`pre-commit run ` 
didn't help

**Comment by jonmeow** [comment]
It's probably complaining about end-of-file newline differences. Running `pre-commit run -a` will check things after you've already committed (short for `--all-files`, there might be a better way, but I haven't memorized it), `pre-commit install` is needed to check prior.

TBH I should maybe exclude the svg files from this particular check, it's pretty low value for them.

**Comment by jonmeow** [comment]
Filed #1655 to remind on svg pre-commit exceptions.

**Review by jonmeow — APPROVED** [review]
Thanks!

**Pull request merged**
