### PR TITLE
Iterate on diagnostic structure

### PR DESCRIPTION
**Pull request by jonmeow**
Part of this is also a plan to change "ERROR:" -> "error:" in diagnostics. I think I'm the odd one out on sentence casing. The rest is mostly trying to figure out advice that I think we can live with.

Note I'm not immediately planning to rewrite all diagnostics (unless maybe there's a simple regex). I'm more trying to redirect style a little to where preferences lie, particularly for new diagnostics.

### CODE REVIEW

**Review by zygoloid — COMMENTED** [review]
Thanks, these guidelines look reasonable to me.

**Review by chandlerc — COMMENTED** [review]
LGTM as well, leaving it for Dave in case he has comments here.

**Comment by dwblaikie** [comment]
Any chance we could include a reference to clang's diagnostic style guide as a baseline+exceptions/clarificaitons for Carbon? (somewhat like carbon's style guide basing on the google style guide) since the existence of these rules is at least partially motivated by compatibility both for the ecosystem in general, and for cases in the future where a single compiler invocation may produce both clang and carbon diagnostics together.

**Comment by jonmeow** [comment]
> Any chance we could include a reference to clang's diagnostic style guide as a baseline+exceptions/clarificaitons for Carbon? (somewhat like carbon's style guide basing on the google style guide) since the existence of these rules is at least partially motivated by compatibility both for the ecosystem in general, and for cases in the future where a single compiler invocation may produce both clang and carbon diagnostics together.

I've added a note that we're trying to be similar. I wasn't taking a "baseline+exceptions" because of a couple reasons:

- While we're trying to be similar to Clang for intermingled diagnostics, we're also trying to stand on our own as a programming language. I want developers to be able to read our documentation and understand what to do, without looking at Clang's documentation (which also differs for the basic `%0` versus `{0}` in examples).

- A fair amount of the prior phrasing feels to me like it's trying to address things similar to what Clang's diagnostic wording is, but in a slightly different way, and so I'm not quite sure how to phrase that as "+exceptions" without rewriting most of either or both.

**Review by dwblaikie — APPROVED** [review]

**Pull request merged**
