### PR TITLE
move highlightjs code into utils directory

### PR DESCRIPTION
**Pull request by junlarsen**
Following a short discussion on Discord about where to locate developer tools, I suggest we collect developer utils inside a `/utils` directory at the repository root.

The idea behind this directory is taken from LLVM's utils directories in the various LLVM subprojects which host tooling such as Vim and VSCode extensions, utility scripts, and other useful bits for developers developing or using LLVM.

This patch moves the highlightjs code into said utils directory.

Let me know if there's anything else that's missing :smile:

cc @jonmeow

### CODE REVIEW

**Comment by jonmeow** [comment]
This looks good to me, but prettier will probably ask for formatting fixes. If you use pre-commit (https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#pre-commit) it'll fix a lot of that for you up front.

**Comment by junlarsen** [comment]
> This looks good to me, but prettier will probably ask for formatting fixes. If you use pre-commit ([`trunk`/docs/project/contribution_tools.md#pre-commit](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md?rgh-link-date=2022-07-20T18%3A55%3A15Z#pre-commit)) it'll fix a lot of that for you up front.

Ah, that's excellent! Re-applied the commit with the fixes - thanks!

**Review by jonmeow — APPROVED** [review]
Thanks!

I do want to note we avoid using force-pushes because GitHub's comment system is happier if you just push new commits. We'll generally squash-merge anyways.

**Comment by junlarsen** [comment]
Cool, will keep that in mind for next time :+1:

**Pull request merged**
