### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by gautam1858**
Refactoring the documentation for better readablity

### CODE REVIEW

**Comment by jonmeow** [comment]
I'm going to leave this to @chandlerc to decide if he wants these changes. Many of them look like they're more subjective improvements. The top-level README is high visibility, and there's already been a lot of review of the phrasing, so I do think subjective changes are more likely to be declined.

**Comment by chandlerc** [comment]
I want to echo some points Jon makes: this is an incredibly high visibility document, and has already had a huge amount of review. I'm quite hesitant to change it's wording without a very clear motivation.

If some of these are just very narrow grammar but fixes, maybe extract those and identify them as such?

For most of what i saw when skimming it looks like they are just alternate ways of phrasing things. I think we would need to really understand the specific problem being addressed before we dig into these. A purely preferential change I think doesn't make sense.

**Comment by gautam1858** [comment]
You are absolutely right. I don't want to justify those but it's just more readable.

Let me contribute more on the coding part.

**Comment by jonmeow** [comment]
It sounds like there's agreement the changes are being retracted in response to chandlerc's comment. I'm closing this PR in order to remove it from the open PR list.

**Pull request closed without merging**
